This is the Jupyter Notebook file for our CSE 404 Group Project. This will be run on Google Colab, and stored on Github at https://github.com/ToffeeNTea/CSE404-Group-Project.git

IN ORDER TO SAVE YOUR CHANGES:
1. Click ```File``` → ```Save a copy in Github```
  - Or just press CTRL + S, it brings up the prompt
2. Select the repository ```ToffeeNTea/CSE404-Group-Project``` under branch ```main```
3. Do not change the filepath
4. Change the commit message
5. Press ```OK```

Run the cell below to load in the GitHub repository. Rerunning the cell will pull any changes to the repository from online. The working directory will be set to the repository.

**NOTE: This does NOT update the current Colab notebook! You will need to open the file from GitHub again!**

In [4]:
# Opens the GitHub repository into the Google Colab environment
# Pulls updates to files (except for the notebook itself) from the repo
# If your notebook seems broken, press Runtime --> Disconnect and delete runtime
import os
import time
from google.colab import userdata

if os.path.exists('/content/CSE404-Group-Project'):
  !rm -rf /content/CSE404-Group-Project  # Delete old files

%cd /content
!git clone https://github.com/ToffeeNTea/CSE404-Group-Project.git
# Working directory set to the repo
%cd /content/CSE404-Group-Project

# Utility stuff
# Set these in Colab's "Secrets" (left side, key symbol)
# try:
#   GITHUB_EMAIL = userdata.get('GITHUB_EMAIL')
#   GITHUB_USERNAME = userdata.get('GITHUB_USERNAME')
#   GITHUB_TOKEN = userdata.get("GITHUB_TOKEN")
#   REPO_NAME = "CSE404-Group-Project"

#   !git config --global user.email "{GITHUB_EMAIL}"
#   !git config --global user.name "{GITHUB_USERNAME}"
#   !git remote set-url origin https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git
# except:
#   print("ERROR: Please set the secret environment variables")
#   print("""You will need to create a Personal Access Token on GitHub.
#     While logged in, go to https://github.com/settings/tokens
#     Generate a new token (classic)
#     Enable the following permissions:
#       - repo
#     Then copy paste into the Secrets (left side, key symbol)
#     """)

# def push_to_github(commit_message="Updated notebook from Colab"):
#   os.system("git add .")
#   os.system(f'git commit -m "{commit_message}"')
#   os.system("git push origin main")

/content
Cloning into 'CSE404-Group-Project'...
remote: Enumerating objects: 9585, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 9585 (delta 10), reused 7 (delta 2), pack-reused 9556 (from 4)
Receiving objects: 100% (9585/9585), 641.26 MiB | 31.76 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Updating files: 100% (10007/10007), done.
/content/CSE404-Group-Project


Run the cell below to push updates from the local repository (Colab) to remote.

**NOTE: This does NOT update the .ipynb file on GitHub! You will still need to save it manually using the steps above.**

In [15]:
import os

image_folder = "../CSE404-Group-Project/database/dataset"
coords_folder = "../CSE404-Group-Project/database/csv_data/coords.csv"
print(len(os.listdir(image_folder)))

10000


In [20]:
import numpy as np
import pandas as pd
import cv2
import os

# Paths
image_folder = "../CSE404-Group-Project/database/dataset"
label_file = "../CSE404-Group-Project/database/csv_data/coords.csv"

# Load labels from CSV
coords_df = pd.read_csv(label_file, header=None, names=["x_coord", "y_coord"])
# labels_df = pd.read_csv(label_file, header=None, names=["x_coord", "y_coord"])
labels = coords_df.values  # Convert to numpy array

# Load and process images
image_data = []
for i in range(len(labels)):  # Assumes images are named 0.png, 1.png, ...
    img_path = os.path.join(image_folder, f"{i}.png")

    # Load and resize the image
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    img_resized = cv2.resize(img, (128, 128))  # Resize to a uniform size
    img_flattened = img_resized.flatten()  # Flatten to 1D array

    image_data.append(img_flattened)

# Convert to numpy array
X = np.array(image_data)
y = np.array(labels)

In [21]:
from skimage.feature import hog

def extract_hog_features(img):
    resized_img = cv2.resize(img, (128, 128))  # Resize to 128x128
    features, _ = hog(resized_img, orientations=9, pixels_per_cell=(8, 8),
                      cells_per_block=(2, 2), block_norm='L2-Hys', visualize=True)
    return features

In [23]:
feature_data = []
for i in range(len(labels)):
    img_path = os.path.join(image_folder, f"{i}.png")
    img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

    # Extract HOG features
    features = extract_hog_features(img)
    feature_data.append(features)

X = np.array(feature_data)

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [28]:
import numpy as np
import pandas as pd

# Define grid size (e.g., 10x10 or any other size)
grid_size = 10  # You can adjust the grid size for better granularity
x_min, x_max = coords_df['x_coord'].min(), coords_df['x_coord'].max()
y_min, y_max = coords_df['y_coord'].min(), coords_df['y_coord'].max()

# Map coordinates to grid cells
def map_to_grid(x, y, grid_size, x_min, x_max, y_min, y_max):
    x_grid = int((x - x_min) / (x_max - x_min) * grid_size)
    y_grid = int((y - y_min) / (y_max - y_min) * grid_size)
    return x_grid * grid_size + y_grid  # Unique grid ID

# Create grid labels for classification
coords_df['grid_label'] = coords_df.apply(lambda row: map_to_grid(row['x_coord'], row['y_coord'],
                                                                   grid_size, x_min, x_max, y_min, y_max), axis=1)

In [29]:
# X contains the flattened image or extracted HOG features
# y_class contains the new grid-based labels
X = np.array(feature_data)  # Feature array from images
y_class = coords_df['grid_label'].values  # New classification labels

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_class, test_size=0.2, random_state=42)

# Train logistic regression with a high iteration limit
clf = LogisticRegression(max_iter=2000)  # Higher max_iter to ensure convergence
clf.fit(X_train, y_train)

# Predict grid labels
y_pred = clf.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay

# Confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Classification report for precision, recall, and F1-score
print("Classification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[11  0  8 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 4  0 13 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  1  0]
 [ 0  0  1 ...  0  1  0]
 [ 0  0  0 ...  0  0  2]]
Classification Report:
               precision    recall  f1-score   support

           1       0.33      0.31      0.32        35
           9       0.00      0.00      0.00         3
          11       0.23      0.28      0.25        46
          12       0.09      0.15      0.11        67
          14       0.00      0.00      0.00        11
          15       0.00      0.00      0.00        12
          18       0.18      0.08      0.11        49
          19       0.25      0.34      0.29        70
          21       0.09      0.08      0.08        25
          22       0.23      0.29      0.26       178
          24       0.59      0.48      0.53        21
          25       0.11      0.07      0.09        40
          28       0.33      0.30      0.31        92
          29       0.19      0.20      0.19 

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [36]:
import os
import numpy as np
import pandas as pd
import torch
import torchvision.transforms as transforms
import torchvision.models as models
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

# Load ResNet and remove classification layer
model = models.resnet50(pretrained=True)
model = torch.nn.Sequential(*list(model.children())[:-1])  # Remove final layer
model.eval()

# Define image transformations
transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Resize image to 224x224
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# Feature extraction function
def extract_features(image_path):
    image = Image.open(image_path).convert("RGB")
    image = transform(image).unsqueeze(0)  # Add batch dimension
    with torch.no_grad():  # No gradients needed
        features = model(image)
    return features.squeeze().numpy().flatten()  # Flatten to 1D

# Load coordinate data (CSV file)
# coords_df = pd.read_csv("/mnt/data/coords.csv")

# Define image folder path
# image_folder = "../../database/dataset"

# Extract features and map labels
features, labels = [], []

# Define grid size for classification (adjust if needed)
grid_size = 10
x_min, x_max = coords_df['x_coord'].min(), coords_df['x_coord'].max()
y_min, y_max = coords_df['y_coord'].min(), coords_df['y_coord'].max()

# Map coordinates to grid cells
def map_to_grid(x, y, grid_size, x_min, x_max, y_min, y_max):
    x_grid = int((x - x_min) / (x_max - x_min) * grid_size)
    y_grid = int((y - y_min) / (y_max - y_min) * grid_size)
    return x_grid * grid_size + y_grid

# Extract features and assign grid labels
for idx, row in coords_df.iterrows():
    image_path = os.path.join(image_folder, f"{idx}.png")
    if os.path.exists(image_path):
        feature_vector = extract_features(image_path)
        features.append(feature_vector)
        grid_label = map_to_grid(row['x_coord'], row['y_coord'], grid_size, x_min, x_max, y_min, y_max)
        labels.append(grid_label)

# Convert to numpy arrays
X = np.array(features)
y = np.array(labels)

/usr/local/lib/python3.11/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100%|██████████| 97.8M/97.8M [00:01<00:00, 89.7MB/s]


In [37]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train logistic regression
clf = LogisticRegression(max_iter=2000)  # Higher max_iter for convergence
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)

In [38]:
# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Generate classification report
print("Classification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[24  0  5 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 4  0 27 ...  0  0  0]
 ...
 [ 0  0  0 ...  2  2  0]
 [ 0  0  0 ...  2  2  1]
 [ 0  0  1 ...  0  1  4]]
Classification Report:
               precision    recall  f1-score   support

           1       0.56      0.69      0.62        35
           9       0.00      0.00      0.00         3
          11       0.43      0.59      0.50        46
          12       0.28      0.36      0.31        67
          14       0.29      0.18      0.22        11
          15       0.00      0.00      0.00        12
          18       0.59      0.45      0.51        49
          19       0.38      0.43      0.40        70
          21       0.30      0.24      0.27        25
          22       0.44      0.47      0.46       178
          24       0.68      0.62      0.65        21
          25       0.28      0.25      0.26        40
          28       0.66      0.73      0.69        92
          29       0.44      0.49      0.47 

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
